// Gent Vigilon Helper. Static GitHub Pages app; no build step required.
const $ = (s, root=document) => root.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storageKey='gv_engineering_v2';
const schema={
 devices:{label:'Devices and labels',fields:['Loop','Address','Device type','Label','Zone','Sector','Group','Day state','Night state','Time block','Status','Notes']},
 zones:{label:'Zones',fields:['Zone','Label','Display mode','Devices','Task / coincidence','Trigger build','Status','Notes']},
 sectors:{label:'Sectors',fields:['Loop','Sector','Label / purpose','Devices / I/O lines','Signals','Silence action','Reset action','Status','Notes']},
 links:{label:'Sector links',fields:['Trigger loop','Trigger sector','Target loop','Target sector','Signal','Delay block','Status','Notes']},
 builds:{label:'Command builds',fields:['Build','Label','Trigger type','Trigger reference','Action','Target','Reversible / latched','Status','Notes']},
 delays:{label:'Delay blocks',fields:['Delay block','Label / purpose','Delay','Trigger','Target','Signal / action','Status','Notes']},
 blocks:{label:'Time blocks',fields:['Time block','Label / purpose','Assigned time slots','Linked devices / builds','Status','Notes']},
 slots:{label:'Time slots',fields:['Time slot','Label / purpose','Enable time','Disable time','Days / dates','AND / OR logic','Time block','Status','Notes']},
 interfaces:{label:'Interfaces',fields:['Loop','Address','Part code','Interface type','Label / location','Channel','Input / output type','Connected equipment','Normal contact state','Zone','Sector','Build / trigger','Output action','Delay','Silence / reset behaviour','Status','Notes']}
};
const fresh=()=>({version:2,site:{name:'',panel:'',job:'',engineer:'',date:'',notes:''},records:Object.fromEntries(Object.keys(schema).map(k=>[k,[]])),basket:[],favourites:[]});
function validate(v){if(!v||v.version!==2||!v.site||!v.records||!Array.isArray(v.basket)||!Array.isArray(v.favourites))return false;for(const k of ['name','panel','job','engineer','date','notes'])if(typeof v.site[k]!=='string')return false;for(const [k,s] of Object.entries(schema)){if(!Array.isArray(v.records[k])||v.records[k].length>10000)return false;for(const r of v.records[k])if(!r||typeof r.id!=='string'||s.fields.some(f=>r[f]!==undefined&&typeof r[f]!=='string'))return false;}return v.favourites.every(x=>typeof x==='string')&&v.basket.every(r=>r&&typeof r.code==='string'&&typeof r.name==='string'&&Number.isSafeInteger(r.qty)&&r.qty>0&&r.qty<=9999&&typeof r.note==='string');}
let state=fresh(),storageProblem=false;
try{const raw=localStorage.getItem(storageKey);if(raw){const v=JSON.parse(raw);if(validate(v))state=v;else storageProblem=true;}}catch{storageProblem=true;}
let data,query='',filter='All',favOnly=false,recordTab='devices',unmountLegacy=null,current='',flowId='tx-fault',flowStep='',flowHistory=[],flowResolution=null,noticeTimer;
function tell(text){const n=$('#notice');n.textContent=text;n.style.display='block';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.style.display='none',4500);}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));storageProblem=false;document.querySelectorAll('.save-state').forEach(e=>e.textContent='Saved on this device');}catch{storageProblem=true;document.querySelectorAll('.save-state').forEach(e=>e.textContent='Save unavailable. Export a backup.');tell('Unable to save on this device. Export a backup to keep these records.');}}
async function copy(text){if(!text.trim()){tell('Nothing to copy yet.');return;}try{await navigator.clipboard.writeText(text);tell('Copied to clipboard');}catch{$('#copy-text').value=text;$('#copy-dialog').showModal();$('#copy-text').select();}}
$('#close-copy').onclick=()=>$('#copy-dialog').close();
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const button=(text,action,extra='')=>`<button type="button" data-action="${action}" ${extra}>${text}</button>`;
const source=(doc,page,label)=>`<a href="reference/${doc}.pdf#page=${page}" target="_blank" rel="noopener">${label} page ${page}</a>`;
const header=(title,desc,actions='')=>`<div class="page-head"><div><div class="eyebrow">FIELD REFERENCE</div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`;
const categories=items=>['All',...new Set(items.map(x=>x.category))];
const select=(id,values,value)=>`<select id="${id}">${values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;
const empty=text=>`<div class="empty">${text}</div>`;
function searchBar(placeholder,cats){return `<div class="toolbar"><label>Search<input id="search" type="search" value="${esc(query)}" placeholder="${placeholder}" autocomplete="off"></label>${cats?`<label>Category${select('filter',cats,filter)}</label>`:''}${current==='faults'||current==='keypad'?button(favOnly?'Show all':'Favourites','favourites',`aria-pressed="${favOnly}"`):''}${button('Clear','clear-search')}</div>`;}
function match(text){let q=query.toLowerCase().trim();const aliases={oc:'split',sc:'short',tx:'tx',mcc:'mcc',mcb:'mcb'};q=aliases[q]||q;const hay=text.toLowerCase();return q.split(/\s+/).every(w=>hay.includes(w));}
function categoryFault(f){const s=(f.message+' '+f.associatedWith).toLowerCase();if(/voice alarm/.test(s))return 'Voice alarm';if(/radio|plexus/.test(s))return 'Radio';if(/network|node|domain/.test(s))return 'Network';if(/battery|batteries|mains|earth|psu|supply|charger/.test(s))return 'Power';if(/nvm|flash|checksum|memory|configuration/.test(s))return 'Configuration';if(/loop|lpc|device|sensor|outstation|allocation/.test(s))return 'Loop and devices';return 'Panel and system';}
function star(id){return button(state.favourites.includes(id)?'Remove favourite':'Save favourite','star',`data-id="${esc(id)}"`);}
function faultCards(){const items=data.faults.filter(x=>(filter==='All'||x.category===filter)&&(!favOnly||state.favourites.includes(x.id))&&match([x.message,x.meaning,x.associatedWith,x.possibleAction].join(' ')));return `<p class="count">${items.length} of ${data.faults.length} messages</p><div class="grid">${items.map(f=>`<article class="card"><div class="meta">${esc(f.category)} / Appendix B, page ${f.page}</div><h2>${esc(f.message)}</h2><p>${esc(f.meaning||'No meaning stated in this entry.')}</p><details><summary>Message reference</summary><dl><dt>Associated equipment</dt><dd>${esc(f.associatedWith||'Not specified')}</dd><dt>Possible action</dt><dd>${esc(f.possibleAction==='-'?'No action specified.':f.possibleAction||'No action specified.')}</dd></dl><p class="meta">${source('commissioning-manual',f.page,'Commissioning manual')}</p><div class="actions">${button('Copy message','copy-fault',`data-id="${f.id}"`)}${star(f.id)}</div></details><div class="actions">${button('Select replacement parts','fault-parts',`data-id="${f.id}"`)}${button('Keypad reference','fault-keys',`data-id="${f.id}"`)}</div></article>`).join('')}</div>${items.length?'':empty('No matching messages. Try a shorter phrase or clear the filters.')}`;}
function keypadCards(){const items=data.keys.filter(x=>(filter==='All'||x.category===filter)&&(!favOnly||state.favourites.includes(x.id))&&match(x.title+' '+x.sequence+' '+x.category));return `<p class="count">${items.length} procedures and examples</p><div class="grid">${items.map(k=>`<article class="card"><div class="meta">${esc(k.category)} / Help sheet, page ${k.page}${k.manualPage?' / Manual cross-check':''}</div><h2>${esc(k.title)}</h2>${k.unresolved?`<div class="source-note">${esc(k.note)}</div><details><summary>Original help-sheet wording</summary><p>${esc(k.sequence)}</p></details>`:`<details><summary>Keypad steps</summary><ol class="steps">${k.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${k.note?`<div class="source-note">${esc(k.note)}</div>`:''}</details>`}<p class="meta">${source('help-sheet',k.page,'Help sheet')}${k.manualPage?' / '+source('commissioning-manual',k.manualPage,'Manual'):''}</p><div class="actions">${!k.unresolved?button('Copy sequence','copy-key',`data-id="${k.id}"`):''}${star(k.id)}</div></article>`).join('')}</div>${items.length?'':empty('No matching procedures. Try allocate, label, sector, time or build.')}`;}
function basketText(){return state.basket.map(r=>`${r.qty} x ${r.code} - ${r.name}${r.note?'\n  '+r.note:''}`).join('\n');}
function basket(){return `<aside class="panel basket" id="basket"><h2>Parts basket</h2><p class="muted">${state.basket.reduce((n,r)=>n+r.qty,0)} items across ${state.basket.length} part numbers</p><div class="save-state">${storageProblem?'Save unavailable. Export a backup.':'Saved on this device'}</div>${state.basket.map((r,i)=>`<div class="basket-row"><div class="code">${esc(r.code)}</div><p>${esc(r.name)}</p><div class="actions"><label>Quantity<input type="number" min="1" max="9999" step="1" value="${r.qty}" data-basket-qty="${i}"></label>${button('Remove','remove-part',`data-index="${i}"`)}</div><label style="max-width:none;margin-top:12px">Location / job note<input data-basket-note="${i}" value="${esc(r.note)}" placeholder="Loop, address or location"></label></div>`).join('')}${state.basket.length?`<div class="actions">${button('Copy parts list','copy-parts','class="primary"')}${button('Empty basket','empty-basket')}</div>`:empty('Select a part and quantity to start a list.')}</aside>`;}
function partCards(){const items=data.parts.filter(p=>(filter==='All'||filter===p.category)&&match(p.code+' '+p.name+' '+p.category));return `<p class="count">${items.length} catalogue entries</p><div class="grid parts-grid">${items.map(p=>`<article class="card"><div class="meta">${esc(p.category)}</div><h2 class="code">${esc(p.code)}</h2><p>${esc(p.name)}</p><details><summary>Specification reference</summary><p>${p.pages.map(n=>source('specification-guide',n,'Guide')).join(' / ')}</p>${p.note?`<p class="source-note">${esc(p.note)}</p>`:''}</details><div class="actions"><label>Quantity<input class="qty" type="number" min="1" max="9999" step="1" value="1" aria-label="Quantity for ${esc(p.code)}" id="qty-${esc(p.code.replaceAll(' ','_'))}"></label>${button('Add to basket','add-part',`data-id="${esc(p.code)}" class="primary"`)}</div></article>`).join('')}</div>${items.length?'':empty('No matching parts. Search by part code or device type.')}`;}
function field(label,value,attrs=''){return `<label ${label==='Notes'?'class="wide"':''}>${esc(label)}${label==='Notes'?`<textarea ${attrs}>${esc(value)}</textarea>`:`<input ${attrs} value="${esc(value)}">`}</label>`;}
function programmingText(){const s=state.site;const lines=['GENT VIGILON - PROGRAMMING RECORD'];for(const [key,label] of Object.entries({name:'Site',panel:'Panel',job:'Job reference',engineer:'Engineer',date:'Date',notes:'Site notes'}))if(s[key])lines.push(`${label}: ${s[key]}`);for(const [key,def] of Object.entries(schema)){const rows=state.records[key].filter(r=>def.fields.some(f=>r[f]?.trim()));if(!rows.length)continue;lines.push('',def.label.toUpperCase());rows.forEach((r,i)=>{lines.push(`Record ${i+1}`);if(key==='links')lines.push(`Trigger: loop ${r['Trigger loop']||'-'}, sector ${r['Trigger sector']||'-'}; Target: loop ${r['Target loop']||'-'}, sector ${r['Target sector']||'-'}`);for(const f of def.fields)if(r[f]?.trim())lines.push(`${f}: ${r[f]}`);});}return lines.join('\n');}
function records(){const def=schema[recordTab];return `<div class="section-head"><div><h2>${def.label}</h2><p class="muted">${recordTab==='links'?'Record the trigger sector first, then the sector it operates.':recordTab==='interfaces'?'Use one record per channel where an interface has several functions.':'Record the values read from the panel or site configuration.'}</p></div>${button('Add record','add-record','class="primary"')}</div><div class="records">${state.records[recordTab].map((r,i)=>`<section class="panel record"><div class="section-head"><h3>${def.label} ${i+1}</h3>${button('Remove record','remove-record',`data-id="${r.id}"`)}</div><div class="form-grid">${def.fields.map(f=>field(f,r[f]||'',`data-record="${r.id}" data-field="${esc(f)}" ${f==='Interface type'?'list="interface-types"':''} ${f==='Part code'?'list="part-codes"':''}`)).join('')}</div></section>`).join('')}${state.records[recordTab].length?'':empty('No records in this section yet. Select Add record to begin.')}</div>`;}
function programming(){return header('Programming record','Capture the site programming and cause and effect.',`<span class="save-state">${storageProblem?'Save unavailable. Export a backup.':'Saved on this device'}</span>${button('Copy programming','copy-programming','class="primary"')}`)+`<section class="panel"><h2>Site details</h2><div class="form-grid" style="margin-top:18px">${Object.entries({name:'Site name',panel:'Panel model / reference',job:'Job reference',engineer:'Engineer',date:'Date',notes:'Notes'}).map(([k,l])=>field(l,state.site[k],`data-site="${k}" ${k==='date'?'type="date"':''}`)).join('')}</div></section><div class="subnav" aria-label="Programming categories">${Object.entries(schema).map(([k,d])=>button(`${d.label} (${state.records[k].length})`,'record-tab',`data-tab="${k}" aria-pressed="${k===recordTab}"`)).join('')}</div><div id="records">${records()}</div><section class="panel" style="margin-top:28px"><details><summary>Review copy text</summary><textarea readonly class="output" id="program-output" aria-label="Programming text">${esc(programmingText())}</textarea></details><div class="actions" style="margin-top:18px">${button('Copy programming','copy-programming','class="primary"')}${button('Export backup','export')}${button('Import backup','import')}${button('Start new job','new-job')}</div><p class="meta">A backup contains the programming record, parts basket and favourites.</p><input hidden type="file" id="import-file" accept="application/json,.json"></section><datalist id="interface-types">${['Single-channel input / zone module','Single-channel input/output','Four-channel input/output','Mains switching output','Mains switching input/output','Mains powered interface','Key-operated non-fire input','12-way non-fire input','FAAST interface'].map(v=>`<option value="${v}">`).join('')}</datalist><datalist id="part-codes">${data.parts.filter(p=>p.category==='Interfaces').map(p=>`<option value="${p.code}">${esc(p.name)}</option>`).join('')}</datalist>`;}
function plain(s){return String(s||'').replace(/[\p{Extended_Pictographic}\uFE0F\u2705\u2713\u26A0]/gu,'').replaceAll('**','').trim();}
function flow(){const flows=window.GVLegacy.flows;const f=flows.find(x=>x.id===flowId)||flows[0];flowId=f.id;if(!flowStep)flowStep=f.initialStepId;const step=f.steps[flowStep];return header('Fault finding','Follow a diagnostic flowchart or open the full message reference.',`<a class="button" href="#faults">Message library</a><a class="button" href="#parts">Select parts</a>`)+`<label>Flowchart<select id="flow-select">${flows.map(x=>`<option value="${x.id}" ${x.id===flowId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><section class="panel flow"><div class="meta">${esc(f.name)}</div>${flowResolution?`<h2>${esc(plain(flowResolution.resolutionText))}</h2><div class="actions">${button('Start again','flow-reset')}<a class="button" href="#parts">Select replacement parts</a></div>`:`<h2>${esc(plain(step.title))}</h2><p>${esc(plain(step.description))}</p>${step.safetyNote?`<p class="source-note">${esc(plain(step.safetyNote))}</p>`:''}<p><strong>${esc(plain(step.question))}</strong></p><div class="actions" style="margin-top:20px">${(step.options||[]).map((o,i)=>button(esc(plain(o.label)),'flow-next',`data-index="${i}"`)).join('')}</div><div class="actions" style="margin-top:22px">${button('Previous step','flow-back',flowHistory.length?'':'disabled')}${button('Start again','flow-reset')}<a class="button" href="#keypad">Keypad reference</a><a class="button" href="#parts">Select replacement parts</a></div>`}</section>`;}
const navs={faults:'Faults',keypad:'Keypad',programming:'Programming',parts:'Parts',flowcharts:'Fault finding',psu:'PSU',sensors:'Sensors',documents:'Documents'};
function route(){let hash=location.hash.slice(1);const aliases={chat:'faults',messages:'faults',audit:'programming',decoder:'sensors',keystrokes:'keypad',sequences:'keypad'};return aliases[hash]|| (navs[hash]?hash:'faults');}
function render(){if(unmountLegacy){unmountLegacy();unmountLegacy=null;}current=route();$('#nav').innerHTML=Object.entries(navs).map(([k,v])=>`<a href="#${k}" ${current===k?'aria-current="page"':''}>${v}</a>`).join('');const main=$('#main');if(current==='faults')main.innerHTML=header('Fault messages','Find a panel message, its meaning and the recommended action.',`<span class="tag">${data.faults.length} Appendix B entries</span>`)+searchBar('Search message, equipment or action',categories(data.faults))+'<div id="results">'+faultCards()+'</div>';if(current==='keypad')main.innerHTML=header('Keypad reference','Find the steps for diagnostics, control and programming. Use the etc key for later menu options.')+searchBar('Search allocate, repair, labels, sectors or builds',categories(data.keys))+'<div id="results">'+keypadCards()+'</div>';if(current==='parts')main.innerHTML=header('Parts library','Select parts and quantities, then copy the list to your job notes.',button('Export backup','export'))+searchBar('Search part number or device type',categories(data.parts))+`<div class="split"><div id="results">${partCards()}</div>${basket()}</div>`;if(current==='programming')main.innerHTML=programming();if(current==='flowcharts')main.innerHTML=flow();if(['psu','sensors'].includes(current)){main.innerHTML=header(current==='psu'?'PSU readings':'Sensor reference','',`<a class="button" href="#keypad">Keypad reference</a><a class="button" href="#parts">Select replacement parts</a>`)+'<div id="legacy"></div>';unmountLegacy=window.GVLegacy.mount($('#legacy'),current==='psu'?'psu':'sensors');}if(current==='documents')main.innerHTML=header('Source documents','Open the supplied Gent references.')+`<div class="panel ref-links"><a class="button" href="reference/commissioning-manual.pdf" target="_blank" rel="noopener">Generic commissioning manual, Issue 9, May 2017</a><a class="button" href="reference/help-sheet.pdf" target="_blank" rel="noopener">Gent Vigilon Help Sheet</a><a class="button" href="reference/specification-guide.pdf" target="_blank" rel="noopener">Consultants Specification Guide, version 1.1, May 2017</a></div><div class="panel" style="margin-top:20px"><h2>Reference notes</h2><p>Appendix B covers fault messages and system events across the panel range, including legacy equipment. Entries retain the manual wording and page references.</p><p>Keypad entries identify their help-sheet page. Where the supplied documents conflict, the affected entry describes the discrepancy. Unresolved paths are shown as source wording without a copy-sequence action.</p><p>The parts catalogue follows the supplied 2017 guide. Variant discrepancies are recorded against the affected parts.</p></div>`;}
function updateResults(){const box=$('#results');if(box)box.innerHTML=current==='faults'?faultCards():current==='keypad'?keypadCards():partCards();}
function go(tab,q='',cat='All'){query=q;filter=cat;favOnly=false;if(location.hash==='#'+tab)render();else {pending=true;location.hash=tab;}}
let pending=false;window.addEventListener('hashchange',()=>{if(!pending){query='';filter='All';favOnly=false;}pending=false;render();window.scrollTo(0,0);});
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vigilon-${(state.site.name||'job').replace(/[^a-z0-9]+/gi,'-')}-backup.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('#main').addEventListener('input',e=>{const t=e.target;if(t.id==='search'){query=t.value;updateResults();}if(t.dataset.site){state.site[t.dataset.site]=t.value;save();}if(t.dataset.record){const r=state.records[recordTab].find(x=>x.id===t.dataset.record);r[t.dataset.field]=t.value;save();}if(t.dataset.basketNote!==undefined){state.basket[+t.dataset.basketNote].note=t.value;save();}if($('#program-output'))$('#program-output').value=programmingText();});
$('#main').addEventListener('change',async e=>{const t=e.target;if(t.id==='filter'){filter=t.value;updateResults();}if(t.dataset.basketQty!==undefined){const n=Number(t.value);if(!Number.isInteger(n)||n<1||n>9999){t.value=state.basket[+t.dataset.basketQty].qty;tell('Enter a whole quantity from 1 to 9999.');return;}state.basket[+t.dataset.basketQty].qty=n;save();$('#basket').outerHTML=basket();}if(t.id==='flow-select'){flowId=t.value;flowStep='';flowHistory=[];flowResolution=null;render();}if(t.id==='import-file'&&t.files[0]){try{if(t.files[0].size>10000000)throw Error('Backup is too large.');const v=JSON.parse(await t.files[0].text());if(!validate(v))throw Error('This is not a valid Vigilon Helper backup.');if(!confirm('Replace this job, basket and favourites with the selected backup?'))return;state=v;save();render();tell('Backup imported.');}catch(err){tell(err.message||'Unable to read backup.');}finally{if(t.isConnected)t.value='';}}});
$('#main').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
if(a==='clear-search'){query='';filter='All';favOnly=false;render();$('#search')?.focus();}
if(a==='favourites'){favOnly=!favOnly;render();}
if(a==='star'){state.favourites=state.favourites.includes(id)?state.favourites.filter(x=>x!==id):[...state.favourites,id];save();b.textContent=state.favourites.includes(id)?'Remove favourite':'Save favourite';if(favOnly)updateResults();}
if(a==='copy-fault'){const f=data.faults.find(x=>x.id===id);copy(`${f.message}\nEquipment: ${f.associatedWith}\nMeaning: ${f.meaning}\nPossible action: ${f.possibleAction}\nCommissioning manual, Appendix B, page ${f.page}`);}
if(a==='copy-key'){const k=data.keys.find(x=>x.id===id);copy(`${k.title}\n${k.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}${k.note?'\n'+k.note:''}\nHelp Sheet page ${k.page}${k.manualPage?'; commissioning manual page '+k.manualPage:''}`);}
if(a==='fault-parts'){const f=data.faults.find(x=>x.id===id);go('parts','',/interface/i.test(f.message+' '+f.associatedWith)?'Interfaces':'All');}
if(a==='fault-keys'){const f=data.faults.find(x=>x.id===id);go('keypad',/allocat/i.test(f.message)?'allocat':/nvm|checksum|flash/i.test(f.message)?'backup':/earth|batt|mains|psu/i.test(f.message)?'PSU':'');}
if(a==='add-part'){const p=data.parts.find(x=>x.code===id);const input=document.getElementById('qty-'+id.replaceAll(' ','_'));const qty=Number(input.value);if(!Number.isInteger(qty)||qty<1||qty>9999){tell('Enter a whole quantity from 1 to 9999.');input.focus();return;}let r=state.basket.find(x=>x.code===id);if(r&&r.qty+qty>9999){tell('Maximum basket quantity is 9999 per part.');return;}if(r)r.qty+=qty;else state.basket.push({code:p.code,name:p.name,qty,note:''});save();$('#basket').outerHTML=basket();tell(`${qty} x ${id} added`);}
if(a==='remove-part'){state.basket.splice(+b.dataset.index,1);save();$('#basket').outerHTML=basket();}
if(a==='empty-basket'&&confirm('Empty the parts basket?')){state.basket=[];save();$('#basket').outerHTML=basket();}
if(a==='copy-parts')copy(basketText());
if(a==='record-tab'){recordTab=b.dataset.tab;render();}
if(a==='add-record'){state.records[recordTab].push({id:uid()});save();render();const inputs=document.querySelectorAll('[data-record]');const first=inputs[inputs.length-schema[recordTab].fields.length];first?.focus();}
if(a==='remove-record'&&confirm('Remove this programming record?')){state.records[recordTab]=state.records[recordTab].filter(x=>x.id!==id);save();render();}
if(a==='copy-programming')copy(programmingText());
if(a==='export')exportBackup();
if(a==='import')$('#import-file').click();
if(a==='new-job'&&confirm('Start a new job and clear programming and basket? Export a backup first if you need this job.')){const fav=state.favourites;state=fresh();state.favourites=fav;save();render();}
if(a==='flow-next'){const f=window.GVLegacy.flows.find(x=>x.id===flowId),step=f.steps[flowStep],o=step.options[+b.dataset.index];if(o.isResolution)flowResolution=o;else{const next=o.nextStepId||o.nextStep;if(next&&f.steps[next]){flowHistory.push(flowStep);flowStep=next;}else{tell('No next step is defined in the original flowchart.');return;}}render();}
if(a==='flow-back'){flowStep=flowHistory.pop()||flowStep;flowResolution=null;render();}
if(a==='flow-reset'){flowStep='';flowHistory=[];flowResolution=null;render();}
});
function setTheme(dark){document.documentElement.classList.toggle('dark',dark);$('#theme').textContent=dark?'Light mode':'Dark mode';try{localStorage.setItem('vigilon_theme',dark?'dark':'light');}catch{}}
let dark=false;try{dark=localStorage.getItem('vigilon_theme')==='dark';}catch{}setTheme(dark);$('#theme').onclick=()=>setTheme(!document.documentElement.classList.contains('dark'));
// Strip decorative pictograms from the two retained tools without changing numeric readings.
const observer=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes){if(!$('#legacy')?.contains(n))continue;const walk=document.createTreeWalker(n,NodeFilter.SHOW_TEXT);const nodes=n.nodeType===3?[n]:[];while(walk.nextNode())nodes.push(walk.currentNode);for(const node of nodes){const cleaned=node.textContent.replace(/[\p{Extended_Pictographic}\uFE0F\u2705\u2713\u2022]/gu,'');if(cleaned!==node.textContent)node.textContent=cleaned;}}});observer.observe($('#main'),{childList:true,subtree:true});
try{const result=await Promise.all(['faults','keypad','parts'].map(async name=>{const r=await fetch(`${name}.json`);if(!r.ok)throw Error('Missing '+name);return r.json();}));await import('./assets/legacy.js');data={faults:result[0].map(f=>({...f,category:categoryFault(f)})),keys:result[1],parts:result[2]};render();if(storageProblem)tell('Saved records could not be loaded. Import a backup or export your current work.');}catch(err){$('#main').innerHTML=empty('The reference files could not load. Check that all files and folders were uploaded to GitHub, then reload.');console.error(err);}
